# Generated by Django 5.0.2 on 2024-02-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(choices=[('usd', 'usd'), ('rub', 'rub')])),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('currency', models.CharField(choices=[('usd', 'usd'), ('rub', 'rub')])),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(choices=[('usd', 'usd'), ('rub', 'rub')])),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Taxes',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(choices=[('usd', 'usd'), ('rub', 'rub')])),
                ('items', models.JSONField(blank=True)),
                ('payment_intent', models.CharField(max_length=255)),
                ('complete', models.BooleanField(default=False)),
                ('discounts', models.ManyToManyField(to='stripe_main.discount')),
                ('taxes', models.ManyToManyField(to='stripe_main.tax')),
            ],
        ),
    ]
