# Generated by Django 5.0.2 on 2024-02-29 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='stripe_main_orders',
        ),
    ]
