# Generated by Django 5.0.2 on 2024-02-29 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_main', '0002_alter_order_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='discount',
            table='stripe_main_discounts',
        ),
        migrations.AlterModelTable(
            name='item',
            table='stripe_main_items',
        ),
        migrations.AlterModelTable(
            name='tax',
            table='stripe_main_taxes',
        ),
    ]
