# Generated by Django 5.0.2 on 2024-02-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_main', '0004_remove_discount_id_alter_discount_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discounts',
            field=models.ManyToManyField(null=True, to='stripe_main.discount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='taxes',
            field=models.ManyToManyField(null=True, to='stripe_main.tax'),
        ),
    ]
