# Generated by Django 5.0.2 on 2024-02-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_main', '0007_order_complete_order_payment_intent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tax',
            options={'verbose_name_plural': 'Taxes'},
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('usd', 'usd'), ('rur', 'rur')], default='usd'),
            preserve_default=False,
        ),
    ]
