# Generated by Django 5.0.2 on 2024-02-27 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_main', '0008_alter_tax_options_order_amount_order_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='currency',
            field=models.CharField(choices=[('usd', 'usd'), ('rur', 'rur')], default='usd'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='stripe_main.discount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stripe_main.tax'),
        ),
    ]
