# Generated by Django 5.0.2 on 2024-02-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_main', '0011_remove_order_discount_remove_order_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
