# Generated by Django 5.0.2 on 2024-02-27 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_main', '0012_tax_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='discountts',
            new_name='discounts',
        ),
    ]
