# Generated by Django 5.0.2 on 2024-02-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_main', '0013_rename_discountts_order_discounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='currency',
            field=models.CharField(choices=[('usd', 'usd'), ('rub', 'rub')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('usd', 'usd'), ('rub', 'rub')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('usd', 'usd'), ('rub', 'rub')]),
        ),
        migrations.AlterField(
            model_name='tax',
            name='currency',
            field=models.CharField(choices=[('usd', 'usd'), ('rub', 'rub')]),
        ),
    ]
